/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#e1c292',
        'on-primary-container': '#858383',
        'on-error': '#ffffff',
        'surface-variant': '#e4e2de',
        'primary-fixed-dim': '#c8c6c5',
        'inverse-surface': '#30312e',
        'tertiary-container': '#1d1b18',
        'on-surface-variant': '#444748',
        'on-secondary-container': '#786139',
        'on-secondary-fixed': '#271900',
        'primary-container': '#1c1b1b',
        'inverse-on-surface': '#f2f0ed',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#1d1b18',
        'secondary-container': '#fedeac',
        'tertiary-fixed-dim': '#cac6c0',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#474746',
        'on-secondary': '#ffffff',
        'surface-container': '#efeeea',
        'tertiary': '#000000',
        'primary': '#161616',
        'primary-fixed': '#e5e2e1',
        'secondary': '#725b33',
        'on-tertiary-container': '#87837e',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#58431e',
        'surface-container-highest': '#e4e2de',
        'outline': '#747878',
        'on-error-container': '#93000a',
        'outline-variant': '#c4c7c7',
        'surface-tint': '#5f5e5e',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'on-tertiary-fixed-variant': '#494642',
        'surface-container-high': '#eae8e4',
        'surface': '#fbf9f5',
        'inverse-primary': '#c8c6c5',
        'on-surface': '#1b1c1a',
        'background': '#fbf9f5',
        'secondary-fixed': '#fedeac',
        'on-background': '#1b1c1a',
        'surface-container-low': '#f5f3ef',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#1c1b1b',
        'tertiary-fixed': '#e7e2db',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-2xl': '4rem',
        'margin-desktop': '4rem',
        'space-lg': '1.5rem',
        'margin': '1.25rem',
        'gutter': '1.5rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-3xl': '6rem',
        'gutter-desktop': '2.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        display: ['var(--font-playfair)', 'serif'],
        body: ['var(--font-jakarta)', 'sans-serif'],
        'editorial-serif': ['var(--font-playfair)', 'serif'],
        'label-caps': ['var(--font-jakarta)', 'sans-serif'],
        'display-xl': ['var(--font-playfair)', 'serif'],
        'headline-lg': ['var(--font-playfair)', 'serif'],
        'headline-md': ['var(--font-playfair)', 'serif'],
        'headline-sm': ['var(--font-playfair)', 'serif'],
      },
    },
  },
  plugins: [],
};
